[package]
name = "create_token_mint"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.0.6"
solana-client = "2.0.6"
spl-token = "6.0.0"
mpl-token-metadata = "4.1.2"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.125"
